services:
  # 1. Tu Backend
  techgear-api:
    build:
      context: ./TechGear.Api
      dockerfile: Dockerfile
    container_name: techgear-backend
    restart: always
    env_file:
      - .env
    ports:
      - "5000:8080" # Tu PC (5000) -> Contenedor (8080)
    depends_on:
      - redis # Espera a que Redis inicie
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Base de datos (Supabase)
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
      # Redis: "redis" es el nombre del servicio de abajo (DNS interno de Docker)
      - ConnectionStrings__Redis=redis
      # Cloudinary & JWT
      - JwtSettings__TokenKey=${JWT_SECRET}
      - Cloudinary__CloudName=${CLOUDINARY_CLOUD}
      - Cloudinary__ApiKey=${CLOUDINARY_KEY}
      - Cloudinary__ApiSecret=${CLOUDINARY_SECRET}

  # 2. Redis (La memoria caché para el Carrito)
  redis:
    image: redis:alpine
    container_name: techgear-redis
    restart: always
    ports:
      - "6379:6379" # Expone el puerto por si quieres conectarte desde fuera (Postman/GUI)